### PR TITLE
New: Allow skipping the `clap` dependency via the `cli` feature.

### PR DESCRIPTION
**Pull request by dbanty**

### CODE REVIEW

**Comment by dbanty** [comment]
I actually don't know if the `cfg` is required here... or what would happen if you tried to build the binary without the feature enabled.

**Comment by nilslice** [comment]
Good call making this optional. 

> I actually don't know if the cfg is required here... or what would happen if you tried to build the binary without the feature enabled.

I think we'd want `cargo build` to fail if the `cli` feature is disabled, with some way of informing the user of the fix. Now, this would fail, but with a message like "consider adding a 'main' function" or somehting. 

We could technically do something like this in `main.rs`: 

```rust
#[cfg(not(feature = "cli"))]
compile_error!("the feature 'cli' must be enabled to build the qcs-sdk-qir CLI");
```

I've tested & pushed up this addition, but feel free to change as you see fit.

**Review by nilslice — APPROVED** [review]
Looks good to me, pending any different ideas/thoughts for the `compile_error!` usage from @dbanty or @kalzoo

**Comment by Shadow53** [comment]
FWIW, there is a way to specify that a certain target (e.g. a binary) [requires certain features](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#binaries). Maybe that is better here?

**Comment by nilslice** [comment]
@Shadow53 - good call, & TIL! If you'd like to update the PR, please feel free 👍

**Comment by Shadow53** [comment]
Updated:

```
$ cargo build --bin main --no-default-features
error: target `main` in package `qcs-sdk-qir` requires the features: `cli`
Consider enabling them by passing, e.g., `--features="cli"`
```

**Pull request merged**
